name: Selenium Tests

on:
  push: # Runs on push events
  schedule: # Runs from Monday to Friday between 17:00 (UTC + 2) 
    - cron: '0 15 * * 1-5'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Removing previous chrome instances on runner
        run: |
          sudo apt purge google-chrome-stable

      - name: Install dependencies
        run: |
          pip install -r selenium/requirements.txt

      - name: Installing all necessary packages
        run: |
          pip install chromedriver-autoinstaller selenium pyvirtualdisplay

      - name: Install xvfb
        run: |
          sudo apt-get install xvfb

      - name: Run tests
        run: |
          cd selenium
          mkdir -p reports
          pytest
        continue-on-error: true

      - name: Set output
        if: success() || failure()
        id: results
        run: echo "artifactPath=selenium/reports/" >> $GITHUB_ENV

      - name: Setup Pages
        uses: actions/configure-pages@v2
  
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: selenium/reports/

      - name: Deploy to Github pages
        id: deploy
        uses: actions/deploy-pages@v1
