name: 17:00 Tests

on:
  push: # Runs on push events
  schedule: # Runs hourly from Monday to Friday between 8:00 and 17:00
    - cron: '0 8-17 * * 1-5'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r selenium/requirements.txt

      - name: Removing previous chrome instances on runner
        run: |
          sudo apt purge google-chrome-stable

      - name: Installing all necessary packages
        run: |
          pip install chromedriver-autoinstaller selenium pyvirtualdisplay

      - name: Install xvfb
        run: |
          sudo apt-get install xvfb

      - name: Run tests
        run: |
          cd selenium
          mkdir -p reports
          pytest
        continue-on-error: true

      - name: Set output
        if: success() || failure()
        id: results
        run: echo "artifactPath=selenium/reports/" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: report_download
          path: selenium/reports/
      
      - name: Setup Pages
        uses: actions/configure-pages@v2
  
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: selenium/reports/

      - name: Deploy to Github pages
        id: deploy
        uses: actions/deploy-pages@v1